from odoo import models, fields, api
import logging

_logger = logging.getLogger(__name__)


class Measurements(models.Model):
    _name = 'patient.monitoring.measurement'
    _description = 'Patient Measurements'
    _inherit = ['mail.thread']
    _order = 'measurement_date desc'

    name = fields.Char(
        string='Reference', required=True, copy=False,
        default=lambda self: self.env['ir.sequence'].next_by_code('patient.monitoring.measurement')
    )
    patient_id = fields.Many2one(
        'patient.monitoring.patient', string='Patient',
        required=True, ondelete='cascade', tracking=True
    )
    medical_record_id = fields.Many2one(
        'patient.monitoring.medical.record', string='Medical Record'
    )
    measurement_date = fields.Datetime(
        string='Measurement Date', default=fields.Datetime.now, required=True
    )
    recorded_by = fields.Many2one('patient.monitoring.staff', string='Recorded By')

    stream_session_id = fields.Char(
        string='Stream Session ID',
        index=True,
        help='UUID generated by the FastAPI microservice when the stream started.'
    )

    heart_rate = fields.Float(string='Heart Rate (bpm)')
    pulse = fields.Float(string='Pulse (bpm)')
    temperature = fields.Float(string='Temperature (°C)')
    oxygen_saturation = fields.Float(string='O2 Saturation (%)')
    respiratory_rate = fields.Float(string='Respiratory Rate (/min)')
    weight = fields.Float(string='Weight (kg)')
    height = fields.Float(string='Height (cm)')
    bmi = fields.Float(string='BMI', compute='_compute_bmi', store=True)
    notes = fields.Text(string='Notes')
    has_anomaly = fields.Boolean(string='Anomaly Detected', default=False, tracking=True)
    anomaly_details = fields.Text(string='Anomaly Details')

    @api.depends('weight', 'height')
    def _compute_bmi(self):
        for rec in self:
            if rec.height and rec.weight:
                rec.bmi = rec.weight / ((rec.height / 100) ** 2)
            else:
                rec.bmi = 0.0

    @api.model_create_multi
    def create(self, vals_list):
        records = super().create(vals_list)
        for record in records:
            record._run_anomaly_detection()
        return records

    def write(self, vals):
        result = super().write(vals)
        vital_fields = ['heart_rate', 'pulse', 'oxygen_saturation', 'respiratory_rate', 'temperature']
        if any(f in vals for f in vital_fields):
            for rec in self:
                rec._run_anomaly_detection()
        return result

    def _run_anomaly_detection(self):
        self.ensure_one()
        anomalies = []
        record = self.medical_record_id
        if not record:
            return

        checks = {
            'heart_rate': (self.heart_rate, 'Heart Rate', record.min_heart_rate, record.max_heart_rate),
            'pulse': (self.pulse, 'Pulse', record.min_pulse, record.max_pulse),
            'oxygen_saturation': (self.oxygen_saturation, 'O2 Saturation', record.min_oxygen_saturation, record.max_oxygen_saturation),
            'respiratory_rate': (self.respiratory_rate, 'Respiratory Rate', record.min_respiratory_rate, record.max_respiratory_rate),
            'temperature': (self.temperature, 'Temperature', record.min_temperature, record.max_temperature),
        }

        for field_key, (value, label, min_val, max_val) in checks.items():
            if not value:
                continue
            if min_val and value < min_val:
                anomalies.append(f"{label}: {value} is below minimum ({min_val})")
            elif max_val and value > max_val:
                anomalies.append(f"{label}: {value} exceeds maximum ({max_val})")

        if anomalies:
            self.write({'has_anomaly': True, 'anomaly_details': '\n'.join(anomalies)})
            self._generate_alert(anomalies)
        else:
            self.write({'has_anomaly': False, 'anomaly_details': False})
            self._resolve_current_alerts()

    def _resolve_current_alerts(self):
        """Mark earlier 'current' alerts for this patient as 'old'.

        An alert is considered old once a subsequent measurement for the same
        patient comes in without any anomaly, indicating that the abnormal
        condition detected at alert-creation time has normalised.

        Only alerts whose triggering measurement is strictly older than this
        measurement are transitioned, so a clean measurement cannot retroactively
        invalidate alerts that were raised after it.
        """
        self.ensure_one()

        current_alerts = self.env['patient.monitoring.alert'].search([
            ('patient_id', '=', self.patient_id.id),
            ('alert_status', '=', 'current'),
            ('measurement_id.measurement_date', '<', self.measurement_date),
        ])

        if current_alerts:
            _logger.info(
                "Measurement %s (patient %s, date %s) is clean — "
                "transitioning %d alert(s) to 'old': %s",
                self.name,
                self.patient_id.name,
                self.measurement_date,
                len(current_alerts),
                current_alerts.mapped('name'),
            )
            current_alerts.mark_as_old()

    def _generate_alert(self, anomalies):
        Alert = self.env['patient.monitoring.alert']
        severity = 'high' if len(anomalies) > 1 else 'medium'
        existing = Alert.search([
            ('measurement_id', '=', self.id),
            ('state', 'in', ['pending', 'acknowledged']),
        ], limit=1)
        if not existing:
            alert = Alert.create({
                'measurement_id': self.id,
                'alert_type': 'anomaly',
                'severity': severity,
                'description': 'Anomaly detected:\n' + '\n'.join(anomalies),
                'state': 'pending',
                'alert_status': 'current',
            })
            alert._notify_medical_staff()

    def action_run_anomaly_detection(self):
        for rec in self:
            rec._run_anomaly_detection()
        return {
            'type': 'ir.actions.client',
            'tag': 'display_notification',
            'params': {
                'title': 'Anomaly Detection Complete',
                'message': 'Analysis finished. Check alerts if anomalies were found.',
                'type': 'success',
            }
        }